baseURL = "https://bencogan1.com/"
languageCode = "en-us"
title = "Ben Cogan"
theme = "writer"
[pagination]
  pagerSize = 100
enableRobotsTXT = true

[params]
  description = "Essays and reflections by Ben Cogan"
  author = "Ben Cogan"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false
  [markup.highlight]
    style = "github"
    lineNos = false

[outputs]
  home = ["HTML", "RSS"]

[taxonomies]
  tag = "tags"

[menu]
  [[menu.main]]
    name = "Essays"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
